# chi square Goodness of Fit Test

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats

In [ ]:
# Flipping a coin
exp = [50, 50]
obs = [40, 60]

In [ ]:
stats.chisquare(obs, exp)

Power_divergenceResult(statistic=4.0, pvalue=0.04550026389635857)

In [ ]:
# By default expected is equally likely
stats.chisquare(obs)

Power_divergenceResult(statistic=4.0, pvalue=0.04550026389635857)

### Die Roll

In [ ]:
obs = [10, 6, 8, 22, 11, 8]

In [ ]:
stats.chisquare(obs)

Power_divergenceResult(statistic=15.215384615384615, pvalue=0.009480606629220312)

### Shirt Sale

In [ ]:
#Shirt Sale
exp_r = pd.Series([0.1, 0.2, 0.4, 0.3])
obs = pd.Series([25, 41, 91, 68])
exp = exp_r * sum(obs)
exp

0    22.5
1    45.0
2    90.0
3    67.5
dtype: float64

In [ ]:
stats.chisquare(obs, exp)

Power_divergenceResult(statistic=0.648148148148148, pvalue=0.8853267818237286)

# Contingency Tables

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats

In [ ]:
sh_op = np.array([[22, 26, 23], [28, 62, 26], [72, 22, 66]])

In [ ]:
sh_op

array([[22, 26, 23],
       [28, 62, 26],
       [72, 22, 66]])

In [ ]:
stats.chi2_contingency(sh_op)

(50.09315721064659,
 3.4527076339398545e-10,
 4,
 array([[24.96253602, 22.50720461, 23.53025937],
        [40.78386167, 36.77233429, 38.44380403],
        [56.25360231, 50.7204611 , 53.0259366 ]]))

In [ ]:
sh_op_df = pd.DataFrame(sh_op, columns=['Shift1', 'Shift2', 'Shift3'], index=['Worker1', 'Worker2', 'Worker3'])
sh_op_df

         Shift1  Shift2  Shift3
Worker1      22      26      23
Worker2      28      62      26
Worker3      72      22      66

In [ ]:
stats.chi2_contingency(sh_op_df)

(50.09315721064659,
 3.4527076339398545e-10,
 4,
 array([[24.96253602, 22.50720461, 23.53025937],
        [40.78386167, 36.77233429, 38.44380403],
        [56.25360231, 50.7204611 , 53.0259366 ]]))

### Day vs Smokers

In [ ]:
tips = sns.load_dataset('tips')

In [ ]:
tips.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
tips.groupby(by = ['day', 'smoker']).count()

             total_bill  tip  sex  time  size
day  smoker
Thur Yes             17   17   17    17    17
     No              45   45   45    45    45
Fri  Yes             15   15   15    15    15
     No               4    4    4     4     4
Sat  Yes             42   42   42    42    42
     No              45   45   45    45    45
Sun  Yes             19   19   19    19    19
     No              57   57   57    57    57

In [ ]:
day_smoker = tips.pivot_table(index='day', columns='smoker', aggfunc='count')['tip']
day_smoker

smoker  Yes  No
day
Thur     17  45
Fri      15   4
Sat      42  45
Sun      19  57

In [ ]:
stats.chi2_contingency(day_smoker)

(25.787216672396262,
 1.0567572499836523e-05,
 3,
 array([[23.63114754, 38.36885246],
        [ 7.24180328, 11.75819672],
        [33.15983607, 53.84016393],
        [28.96721311, 47.03278689]]))

### End of Section 8